/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bai4;

import javax.swing.JOptionPane;

/**
 *
 * @author soang
 */
public class DemoJDialog extends javax.swing.JFrame {

    /**
     * Creates new form DemoJDialog
     */
    public DemoJDialog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btShowMessage = new javax.swing.JButton();
        btShowConfirmDialog = new javax.swing.JButton();
        btShowOptionDialog = new javax.swing.JButton();
        btShowInputDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("IBM Plex Sans", 1, 48)); // NOI18N
        jLabel1.setText("Demo JDialog");

        btShowMessage.setText("Show Message");
        btShowMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowMessageActionPerformed(evt);
            }
        });

        btShowConfirmDialog.setText("Show Confirm Dialog");
        btShowConfirmDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowConfirmDialogActionPerformed(evt);
            }
        });

        btShowOptionDialog.setText("Show Option Dialog");
        btShowOptionDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowOptionDialogActionPerformed(evt);
            }
        });

        btShowInputDialog.setText("Show Input Dialog");
        btShowInputDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowInputDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btShowMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btShowConfirmDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(btShowOptionDialog))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(37, 37, 37)
                .addComponent(btShowInputDialog)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btShowMessage)
                    .addComponent(btShowConfirmDialog)
                    .addComponent(btShowOptionDialog)
                    .addComponent(btShowInputDialog))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btShowMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowMessageActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hello Show message Dialog", "Show Message Dialog", JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_btShowMessageActionPerformed

    private void btShowConfirmDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowConfirmDialogActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Ban co muon thoat khong?", "Show Confirm Dialog", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btShowConfirmDialogActionPerformed

    private void btShowOptionDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowOptionDialogActionPerformed
        // TODO add your handling code here:
        String[] opt={"Lập trình Java", "Lập trình Anđroid","Lập trình PHP"};
        int choice = JOptionPane.showOptionDialog(this, "Các khóa học của bạn", "Question", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opt, EXIT_ON_CLOSE);
    }//GEN-LAST:event_btShowOptionDialogActionPerformed

    private void btShowInputDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowInputDialogActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog(this, "Nhap Ho Va Ten: ", "Input", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btShowInputDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoJDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btShowConfirmDialog;
    private javax.swing.JButton btShowInputDialog;
    private javax.swing.JButton btShowMessage;
    private javax.swing.JButton btShowOptionDialog;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
