/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bai2;

import java.awt.Color;

/**
 *
 * @author soang
 */
public class ChoiceColor extends javax.swing.JFrame {

    /**
     * Creates new form ChoiceColor
     */
    public ChoiceColor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGrColor = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bRed = new javax.swing.JRadioButton();
        bBlue = new javax.swing.JRadioButton();
        bGreen = new javax.swing.JRadioButton();
        bBlack = new javax.swing.JRadioButton();
        lblMessage = new javax.swing.JLabel();

        BGrColor.add(bRed);
        BGrColor.add(bBlue);
        BGrColor.add(bGreen);
        BGrColor.add(bBlack);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        bRed.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        bRed.setText("Red");
        bRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRedActionPerformed(evt);
            }
        });

        bBlue.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        bBlue.setText("Blue");
        bBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBlueActionPerformed(evt);
            }
        });

        bGreen.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        bGreen.setText("Green");
        bGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGreenActionPerformed(evt);
            }
        });

        bBlack.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        bBlack.setText("Black");
        bBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBlackActionPerformed(evt);
            }
        });

        lblMessage.setFont(new java.awt.Font("IBM Plex Sans", 1, 24)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bBlack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bGreen)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRed, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 121, Short.MAX_VALUE))
            .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bRed, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRedActionPerformed
        // TODO add your handling code here:
        lblMessage.setText("<html>Red is selected</html>");
        lblMessage.setForeground(java.awt.Color.WHITE);
        lblMessage.setBackground(java.awt.Color.RED);
        lblMessage.setOpaque(true);
    }//GEN-LAST:event_bRedActionPerformed

    private void bBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBlueActionPerformed
        // TODO add your handling code here:
        lblMessage.setText("<html>Blue is selected</html>");
        lblMessage.setForeground(java.awt.Color.WHITE);
        lblMessage.setBackground(java.awt.Color.BLUE);
        lblMessage.setOpaque(true);
    }//GEN-LAST:event_bBlueActionPerformed

    private void bGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGreenActionPerformed
        // TODO add your handling code here:
        lblMessage.setText("<html>Green is selected</html>");
        lblMessage.setForeground(java.awt.Color.WHITE);
        lblMessage.setBackground(java.awt.Color.GREEN);
        lblMessage.setOpaque(true);
    }//GEN-LAST:event_bGreenActionPerformed

    private void bBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBlackActionPerformed
        // TODO add your handling code here:
        lblMessage.setText("<html>Black is selected</html>");
        lblMessage.setForeground(java.awt.Color.WHITE);
        lblMessage.setBackground(java.awt.Color.BLACK);
        lblMessage.setOpaque(true);
    }//GEN-LAST:event_bBlackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoiceColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoiceColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoiceColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoiceColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoiceColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGrColor;
    private javax.swing.JRadioButton bBlack;
    private javax.swing.JRadioButton bBlue;
    private javax.swing.JRadioButton bGreen;
    private javax.swing.JRadioButton bRed;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
